syntax = "proto3";

package services;

option go_package = "cim-backend/proto/services";

// ExcelService provides Excel file operations
service ExcelService {
  // Verify Excel file and sheet
  rpc VerifyExcelFile(VerifyExcelFileRequest) returns (VerifyExcelFileResponse);
}

// VerifyExcelFileRequest represents request to verify Excel file
message VerifyExcelFileRequest {
  string filepath = 1;
  string sheetname = 2;
}

// VerifyExcelFileResponse represents response after verifying Excel file
message VerifyExcelFileResponse {
  string message = 1;
  bool valid = 2;
}
