services:
  postgres:
    image: postgres:15-alpine
    container_name: cim_postgres
    environment:
      POSTGRES_DB: cim_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - cim_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cim_backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - cim_network
    volumes:
      - ./uploads:/app/uploads

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: cim_pgweb
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/cim_db?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - cim_network

networks:
  cim_network:
    driver: bridge
