DROP INDEX IF EXISTS idx_units_base_unit;

ALTER TABLE units
    DROP CONSTRAINT IF EXISTS fk_units_base_unit;

ALTER TABLE units
    DROP COLUMN IF EXISTS base_unit_id;

ALTER TABLE units
    ADD COLUMN IF NOT EXISTS is_base BOOLEAN NOT NULL DEFAULT FALSE;
