syntax = "proto3";

package models;

option go_package = "cim-backend/proto/models";

import "google/protobuf/struct.proto";

// Settings represents application settings
message Settings {
  string key = 1;
  google.protobuf.Value value = 2;
}

// SetSettingRequest represents the request to set a setting
message SetSettingRequest {
  string key = 1;
  google.protobuf.Value value = 2;
}

// SetSettingResponse represents the response after setting a value
message SetSettingResponse {
  string message = 1;
}

// GetSettingsResponse represents the response for getting all settings
message GetSettingsResponse {
  repeated Settings data = 1;
}
