package handlers

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"import-export-backend/internal/middleware"
	"import-export-backend/internal/mocks/repositorymocks"
	"import-export-backend/internal/mocks/servicemocks"
	"import-export-backend/internal/models"
	"import-export-backend/pkg"

	"github.com/labstack/echo/v4"
	"github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

func TestCreatePurchaseOrder(t *testing.T) {
	type testSetup struct {
		mockRepo    *repositorymocks.PurchaseOrderRepository
		mockService *servicemocks.PurchaseOrderService
		handler     *PurchaseOrderHandler
		echo        *echo.Echo
	}

	setupTest := func(t *testing.T) *testSetup {
		mockRepo := repositorymocks.NewPurchaseOrderRepository(t)
		mockService := servicemocks.NewPurchaseOrderService(t)
		logger := logrus.New()
		handler := NewPurchaseOrderHandler(mockRepo, mockService, logger)
		e := echo.New()

		// Set up the custom error handler to properly handle validation errors
		e.HTTPErrorHandler = middleware.CustomErrorHandler

		return &testSetup{
			mockRepo:    mockRepo,
			mockService: mockService,
			handler:     handler,
			echo:        e,
		}
	}

	t.Run("should return success case with all fields populated", func(t *testing.T) {
		setup := setupTest(t)

		requestBody := models.PurchaseOrder{
			OrderNumber: "PO-001",
			Status:      models.PurchaseOrderStatusOrderPlaced,
			TotalAmount: 1500.50,
			Notes:       "Test purchase order with all fields",
			Items: []*models.PurchaseOrderItem{
				{
					ProductID:   pkg.Ptr(uint(1)),
					SupplierID:  pkg.Ptr(uint(1)),
					Quantity:    5,
					TotalAmount: 502.50,
				},
				{
					ProductID:   pkg.Ptr(uint(1)),
					SupplierID:  pkg.Ptr(uint(1)),
					Quantity:    10,
					TotalAmount: 2502.50,
				},
			},
		}

		// Setup mock - handler calls service now
		setup.mockService.On("CreatePurchaseOrder", mock.Anything, mock.AnythingOfType("*models.PurchaseOrder")).Return(nil)

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions
		responseOrder := assertSuccessResponse(t, rec, http.StatusCreated)
		assert.Equal(t, requestBody.OrderNumber, responseOrder.OrderNumber)
		assert.Equal(t, requestBody.TotalAmount, responseOrder.TotalAmount)
		assert.Equal(t, requestBody.Notes, responseOrder.Notes)
		assert.Equal(t, requestBody.CreatedBy, responseOrder.CreatedBy)
	})

	t.Run("should generate order number automatically when not provided", func(t *testing.T) {
		setup := setupTest(t)

		requestBody := models.PurchaseOrder{
			// OrderNumber is empty - should be auto-generated by service
			Status:      models.PurchaseOrderStatusOrderPlaced,
			TotalAmount: 1500.50,
			Notes:       "Test purchase order without order number",
			Items: []*models.PurchaseOrderItem{
				{
					ProductID:   pkg.Ptr(uint(1)),
					SupplierID:  pkg.Ptr(uint(1)),
					Quantity:    5,
					TotalAmount: 502.50,
				},
			},
		}

		// Setup mock - service will auto-generate order number
		setup.mockService.On("CreatePurchaseOrder", mock.Anything, mock.AnythingOfType("*models.PurchaseOrder")).Return(nil)

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions
		responseOrder := assertSuccessResponse(t, rec, http.StatusCreated)
		assert.Equal(t, requestBody.TotalAmount, responseOrder.TotalAmount)
		assert.Equal(t, requestBody.Notes, responseOrder.Notes)
		// Note: We can't assert the exact order number here since it's auto-generated by the service
		// The service layer tests will verify the order number generation logic
	})

	t.Run("should return internal server error when repository returns error", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		requestBody := models.PurchaseOrder{
			OrderNumber: "PO-003",
			Items: []*models.PurchaseOrderItem{
				{
					ProductID:   pkg.Ptr(uint(1)),
					SupplierID:  pkg.Ptr(uint(1)),
					Quantity:    5,
					TotalAmount: 502.50,
				},
			},
		}

		// Setup mock - service returns error
		setup.mockService.On("CreatePurchaseOrder", mock.Anything, mock.AnythingOfType("*models.PurchaseOrder")).Return(errors.New("service error"))

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions
		assertErrorResponse(t, rec, http.StatusInternalServerError, "Failed to create purchase order")
	})

	t.Run("should return bad request when request body is invalid data types", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		requestBody := map[string]interface{}{
			"order_number": "PO-004",
			"total_amount": "invalid_amount", // Invalid type
		}

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions
		assertErrorResponse(t, rec, http.StatusBadRequest, "Invalid request body")
	})

	t.Run("should return bad request when request body is invalid JSON", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		requestBody := `{"invalid": json}` // Invalid JSON

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions
		assertErrorResponse(t, rec, http.StatusBadRequest, "Invalid request body")
	})

	t.Run("should return bad request when request body is empty", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", "")
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions - should fail validation due to missing required items
		assertValidationErrorResponse(t, rec)
	})

	t.Run("should return bad request when items field is missing", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		requestBody := models.PurchaseOrder{
			OrderNumber: "PO-005",
			Status:      models.PurchaseOrderStatusOrderPlaced,
			TotalAmount: 1500.50,
			Notes:       "Test purchase order without items",
			// Items field is missing - should fail validation
		}

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions
		assertValidationErrorResponse(t, rec)
	})

	t.Run("should return bad request when items field is empty array", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		requestBody := models.PurchaseOrder{
			OrderNumber: "PO-006",
			Status:      models.PurchaseOrderStatusOrderPlaced,
			TotalAmount: 1500.50,
			Notes:       "Test purchase order with empty items",
			Items:       []*models.PurchaseOrderItem{}, // Empty array - should fail validation (min=1)
		}

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions
		assertValidationErrorResponse(t, rec)
	})

	t.Run("should return bad request when item product_id is missing", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		requestBody := models.PurchaseOrder{
			OrderNumber: "PO-007",
			Status:      models.PurchaseOrderStatusOrderPlaced,
			TotalAmount: 1500.50,
			Notes:       "Test purchase order with invalid item",
			Items: []*models.PurchaseOrderItem{
				{
					// ProductID is nil - should fail validation (required)
					ProductID:   nil,
					SupplierID:  pkg.Ptr(uint(1)),
					Quantity:    5,
					TotalAmount: 502.50,
				},
			},
		}

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions - should fail validation due to required ProductID
		assertValidationErrorResponse(t, rec)
	})

	t.Run("should return bad request when item quantity is zero", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		requestBody := models.PurchaseOrder{
			OrderNumber: "PO-008",
			Status:      models.PurchaseOrderStatusOrderPlaced,
			TotalAmount: 1500.50,
			Notes:       "Test purchase order with invalid quantity",
			Items: []*models.PurchaseOrderItem{
				{
					ProductID:   pkg.Ptr(uint(1)),
					SupplierID:  pkg.Ptr(uint(1)),
					Quantity:    0, // Zero quantity - should fail validation (min=1)
					TotalAmount: 502.50,
				},
			},
		}

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions - this should fail validation due to min=1
		assertValidationErrorResponse(t, rec)
	})

	t.Run("should return bad request when item quantity is negative", func(t *testing.T) {
		// Setup
		setup := setupTest(t)

		requestBody := models.PurchaseOrder{
			OrderNumber: "PO-009",
			Status:      models.PurchaseOrderStatusOrderPlaced,
			TotalAmount: 1500.50,
			Notes:       "Test purchase order with negative quantity",
			Items: []*models.PurchaseOrderItem{
				{
					ProductID:   pkg.Ptr(uint(1)),
					SupplierID:  pkg.Ptr(uint(1)),
					Quantity:    -5, // Negative quantity - should fail validation (min=1)
					TotalAmount: 502.50,
				},
			},
		}

		// Create request and context
		req, err := createRequest(http.MethodPost, "/purchase-orders", requestBody)
		require.NoError(t, err)
		rec := httptest.NewRecorder()
		c := setup.echo.NewContext(req, rec)

		// Execute
		err = setup.handler.CreatePurchaseOrder(c)
		if err != nil {
			setup.echo.HTTPErrorHandler(err, c)
		}

		// Assertions - this should fail validation due to min=1
		assertValidationErrorResponse(t, rec)
	})
}
