// Code generated by "stringer -type=AuthContextKey"; DO NOT EDIT.

package pkg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthContextKeyUserID-0]
	_ = x[AuthContextKeyUserEmail-1]
	_ = x[AuthContextKeyUserName-2]
	_ = x[AuthContextKeyUserRole-3]
	_ = x[AuthContextKeyUserPermissions-4]
	_ = x[AuthContextKeyEnforcementSubject-5]
}

const _AuthContextKey_name = "AuthContextKeyUserIDAuthContextKeyUserEmailAuthContextKeyUserNameAuthContextKeyUserRoleAuthContextKeyUserPermissionsAuthContextKeyEnforcementSubject"

var _AuthContextKey_index = [...]uint8{0, 20, 43, 65, 87, 116, 148}

func (i AuthContextKey) String() string {
	if i < 0 || i >= AuthContextKey(len(_AuthContextKey_index)-1) {
		return "AuthContextKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthContextKey_name[_AuthContextKey_index[i]:_AuthContextKey_index[i+1]]
}
