// Code generated by "stringer -type=ErrorCode -linecomment"; DO NOT EDIT.

package pkg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorCodeInternal-0]
	_ = x[ErrorCodeInvalidRequestBody-1]
	_ = x[ErrorCodeNotFound-2]
	_ = x[ErrorCodeUnauthorized-3]
	_ = x[ErrorCodeForbidden-4]
	_ = x[ErrorCodeValidation-5]
	_ = x[ErrorCodeDuplicate-6]
	_ = x[ErrorCodeConflict-9]
	_ = x[ErrorCodePurchaseOrderNoItems-7]
	_ = x[ErrorCodePurchaseOrderNoApprovedPaymentReceipt-14]
	_ = x[ErrorCodeDuplicateOrderNumber-18]
	_ = x[ErrorCodeBadInventoryItemState-8]
	_ = x[ErrorCodeReconcileValidationFailed-10]
	_ = x[ErrorCodeActivePendingReconcileConflict-17]
	_ = x[ErrorCodeDisposeValidationFailed-11]
	_ = x[ErrorCodeTransferValidationFailed-12]
	_ = x[ErrorCodeConsumeFIFOFailed-13]
	_ = x[ErrorCodeUnsupportedFileFormat-15]
	_ = x[ErrorCodeEmptyDataFile-16]
}

const _ErrorCode_name = "internalinvalid-request-bodynot-foundunauthorizedforbiddenvalidationduplicatepurchase-order-no-itemsbad-inventory-item-stateconflictreconcile-validation-faileddispose-validation-failedtransfer-validation-failedconsume-fifo-failedpurchase-order-no-approved-payment-receiptunsupported-file-formatdata-row-not-foundactive-pending-reconcile-conflictduplicate-order-number"

var _ErrorCode_index = [...]uint16{0, 8, 28, 37, 49, 58, 68, 77, 100, 124, 132, 159, 184, 210, 229, 271, 294, 312, 345, 367}

func (i ErrorCode) String() string {
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
