// Code generated by "stringer -type=ErrorCode -linecomment"; DO NOT EDIT.

package pkg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorCodeInternal-0]
	_ = x[ErrorCodeInvalidRequestBody-1]
	_ = x[ErrorCodeNotFound-2]
	_ = x[ErrorCodeUnauthorized-3]
	_ = x[ErrorCodeForbidden-4]
	_ = x[ErrorCodeValidation-5]
	_ = x[ErrorCodeDuplicate-6]
	_ = x[ErrorCodeConflict-9]
	_ = x[ErrorCodePurchaseOrderNoItems-7]
	_ = x[ErrorCodeBadInventoryItemState-8]
}

const _ErrorCode_name = "internalinvalid-request-bodynot-foundunauthorizedforbiddenvalidationduplicatepurchase-order-no-itemsbad-inventory-item-stateconflict"

var _ErrorCode_index = [...]uint8{0, 8, 28, 37, 49, 58, 68, 77, 100, 124, 132}

func (i ErrorCode) String() string {
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
